# !/bin/bash


sudo pacman -Sy archlinux-keyring && sudo pacman -Syyu

# enable flatpaks
sudo pacman -S --noconfirm --needed flatpak

###### yay ########
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd

###### paru ########
yay -S --noconfirm --needed paru 

###### swayfx ########

yay -S --noconfirm --needed  waybar nwg-panel nwg-launchers wofi mako avizo alacritty wf-recorder wl-clipboard swww swaybg wdisplay waypaper picom polykit nwg-look fuzzel qt5ct qt6ct alacritty kitty xsettingsd swaybg swayidle swaylock wofi wlroots wayland wayland-protocols light grim XWayland slurp wlr-randr wayland-utils google-chrome vscodium swappy smplayer qbittorrent pulse psd pamac menus micro mpv nitrogen feh nwg-drawer octopi pacseek autostart azote bleachbit catfish deluge easyeffects falkon fish foot galculator kvantum wlogout neovim vim nano sudo wl-clipboard grim slurp swappy qt5ct qt5-wayland qt6ct qt6-wayland xdg-desktop-portal-wlr xorg-xwayland xorg-xrandr mesa vulkan-radeon libva-mesa-driver firefox libreoffice-fresh gimp imv spotify mpv mpv-mpris thunar xdg-user-dirs zsh git neofetch htop btop reflector ttf-dejavu ttf-liberation ttf-nerd-fonts-symbols-2048-em noto-fonts noto-fonts-emoji noto-fonts-cjk noto-fonts-extra bc
jq p7zip playerctl python-gobject libnotify bluez-utils lm_sensors imagemagick 

# sddm
sudo pacman -S --noconfirm --needed sddm
sudo systemctl enable sddm.service

###### Packages ########
yay -S --noconfirm --needed acpi
yay -S --noconfirm --needed adobe-source-han-sans-cn-fonts
yay -S --noconfirm --needed adobe-source-han-sans-jp-fonts
yay -S --noconfirm --needed adobe-source-han-sans-kr-fonts
yay -S --noconfirm --needed adobe-source-sans-fonts
yay -S --noconfirm --needed adobe-source-serif-fonts
yay -S --noconfirm --needed aic94xx-firmware
yay -S --noconfirm --needed alacritty
yay -S --noconfirm --needed alacritty-themes
yay -S --noconfirm --needed alsa-firmware
yay -S --noconfirm --needed alsa-plugins
yay -S --noconfirm --needed alsa-utils
yay -S --noconfirm --needed amd-ucode
yay -S --noconfirm --needed appimagelauncher
yay -S --noconfirm --needed appstream
yay -S --noconfirm --needed appstream-glib
yay -S --noconfirm --needed appstream-qt5
yay -S --noconfirm --needed aquamarine
yay -S --noconfirm --needed arandr
yay -S --noconfirm --needed arch-gaming-meta
yay -S --noconfirm --needed arch-install-scripts
yay -S --noconfirm --needed arch-update
yay -S --noconfirm --needed archlinux-tweak-tool-git
yay -S --noconfirm --needed arconet-variety-config
yay -S --noconfirm --needed ardour
yay -S --noconfirm --needed aria2
yay -S --noconfirm --needed arj
yay -S --noconfirm --needed atril
yay -S --noconfirm --needed audacity
yay -S --noconfirm --needed autotiling
yay -S --noconfirm --needed avahi
yay -S --noconfirm --needed awesome-terminal-fonts
yay -S --noconfirm --needed aylurs-gtk-shell
yay -S --noconfirm --needed azote
yay -S --noconfirm --needed b43-fwcutter
yay -S --noconfirm --needed baobab
yay -S --noconfirm --needed base
yay -S --noconfirm --needed base-devel
yay -S --noconfirm --needed bash-completion
yay -S --noconfirm --needed bat
yay -S --noconfirm --needed bc
yay -S --noconfirm --needed bibata-cursor-theme-bin
yay -S --noconfirm --needed bibata-cursor-translucent
yay -S --noconfirm --needed bibata-extra-cursor-theme
yay -S --noconfirm --needed bibata-rainbow-cursor-theme
yay -S --noconfirm --needed bind
yay -S --noconfirm --needed bitwarden
yay -S --noconfirm --needed bleachbit
yay -S --noconfirm --needed blender
yay -S --noconfirm --needed bottles
yay -S --noconfirm --needed boxtron
yay -S --noconfirm --needed brave-bin
yay -S --noconfirm --needed breeze
yay -S --noconfirm --needed brightnessctl
yay -S --noconfirm --needed brltty
yay -S --noconfirm --needed broadcom-wl-dkms
yay -S --noconfirm --needed btop
yay -S --noconfirm --needed btrfs-assistant
yay -S --noconfirm --needed btrfs-du
yay -S --noconfirm --needed btrfs-progs
yay -S --noconfirm --needed btrfsmaintenance
yay -S --noconfirm --needed calf
yay -S --noconfirm --needed carla
yay -S --noconfirm --needed catfish
yay -S --noconfirm --needed catppuccin-cursors-git
yay -S --noconfirm --needed cava
yay -S --noconfirm --needed chiaki
yay -S --noconfirm --needed clapper
yay -S --noconfirm --needed cliphist
yay -S --noconfirm --needed clonezilla
yay -S --noconfirm --needed cloud-init
yay -S --noconfirm --needed codeblocks
yay -S --noconfirm --needed conky-lua-archers
yay -S --noconfirm --needed cpuid
yay -S --noconfirm --needed cpupower
yay -S --noconfirm --needed cryptsetup
yay -S --noconfirm --needed cups
yay -S --noconfirm --needed cups-pdf
yay -S --noconfirm --needed cups-pk-helper
yay -S --noconfirm --needed curl
yay -S --noconfirm --needed darkhttpd
yay -S --noconfirm --needed darktable
yay -S --noconfirm --needed ddrescue
yay -S --noconfirm --needed deluge
yay -S --noconfirm --needed dex
yay -S --noconfirm --needed dhclient
yay -S --noconfirm --needed dhcpcd
yay -S --noconfirm --needed dialog
yay -S --noconfirm --needed diffutils
yay -S --noconfirm --needed digikam
yay -S --noconfirm --needed discord
yay -S --noconfirm --needed dmenu
yay -S --noconfirm --needed dmidecode
yay -S --noconfirm --needed dmraid
yay -S --noconfirm --needed dnsmasq
yay -S --noconfirm --needed docker-compose
yay -S --noconfirm --needed dosfstools
yay -S --noconfirm --needed dotnet-host
yay -S --noconfirm --needed dotnet-runtime
yay -S --noconfirm --needed downgrade
yay -S --noconfirm --needed dracula-cursors-git
yay -S --noconfirm --needed dracula-gtk-theme
yay -S --noconfirm --needed dracula-icons-git
yay -S --noconfirm --needed dracut
yay -S --noconfirm --needed duf
yay -S --noconfirm --needed dunst
yay -S --noconfirm --needed dvgrab
yay -S --noconfirm --needed dxvk-bin
yay -S --noconfirm --needed e2fsprogs
yay -S --noconfirm --needed easyeffects
yay -S --noconfirm --needed edid-decode-git
yay -S --noconfirm --needed edk2-shell
yay -S --noconfirm --needed efibootmgr
yay -S --noconfirm --needed enchant
yay -S --noconfirm --needed eog
yay -S --noconfirm --needed epiphany
yay -S --noconfirm --needed espeakup
yay -S --noconfirm --needed ethtool
yay -S --noconfirm --needed evince
yay -S --noconfirm --needed exfatprogs
yay -S --noconfirm --needed exo
yay -S --noconfirm --needed expac
yay -S --noconfirm --needed eza
yay -S --noconfirm --needed f2fs-tools
yay -S --noconfirm --needed fail2ban
yay -S --noconfirm --needed falkon
yay -S --noconfirm --needed fastfetch
yay -S --noconfirm --needed fatresize
yay -S --noconfirm --needed feh
yay -S --noconfirm --needed ffmpegthumbnailer
yay -S --noconfirm --needed ffmpegthumbs
yay -S --noconfirm --needed file-roller
yay -S --noconfirm --needed filezilla
yay -S --noconfirm --needed firefox
yay -S --noconfirm --needed firefox-ublock-origin
yay -S --noconfirm --needed firejail
yay -S --noconfirm --needed fish
yay -S --noconfirm --needed flameshot-git
yay -S --noconfirm --needed flashplugin
yay -S --noconfirm --needed flat-remix-git
yay -S --noconfirm --needed flatpak
yay -S --noconfirm --needed flavours
yay -S --noconfirm --needed fluent-gtk-theme
yay -S --noconfirm --needed font-manager
yay -S --noconfirm --needed foomatic-db
yay -S --noconfirm --needed foomatic-db-engine
yay -S --noconfirm --needed foomatic-db-gutenprint-ppds
yay -S --noconfirm --needed foomatic-db-nonfree
yay -S --noconfirm --needed foomatic-db-nonfree-ppds
yay -S --noconfirm --needed foomatic-db-ppds
yay -S --noconfirm --needed foot
yay -S --noconfirm --needed fsarchiver
yay -S --noconfirm --needed fuse2fs
yay -S --noconfirm --needed fuzzel
yay -S --noconfirm --needed fwupd
yay -S --noconfirm --needed fzf
yay -S --noconfirm --needed galculator
yay -S --noconfirm --needed gamemode
yay -S --noconfirm --needed gamescope
yay -S --noconfirm --needed garcon
yay -S --noconfirm --needed gawk
yay -S --noconfirm --needed gdb
yay -S --noconfirm --needed geany
yay -S --noconfirm --needed geany-plugins
yay -S --noconfirm --needed gedit
yay -S --noconfirm --needed geekbench
yay -S --noconfirm --needed gimp
yay -S --noconfirm --needed git
yay -S --noconfirm --needed gitahead-git
yay -S --noconfirm --needed gitfiend
yay -S --noconfirm --needed gitg
yay -S --noconfirm --needed github-cli
yay -S --noconfirm --needed github-desktop-bin
yay -S --noconfirm --needed gitkraken
yay -S --noconfirm --needed gittyup-git
yay -S --noconfirm --needed gksu
yay -S --noconfirm --needed glava
yay -S --noconfirm --needed gmtp
yay -S --noconfirm --needed gnome-disk-utility
yay -S --noconfirm --needed gnu-netcat
yay -S --noconfirm --needed google-chrome
yay -S --noconfirm --needed goverlay
yay -S --noconfirm --needed goverlay-bin
yay -S --noconfirm --needed gpart
yay -S --noconfirm --needed gparted
yay -S --noconfirm --needed gpm
yay -S --noconfirm --needed gptfdisk
yay -S --noconfirm --needed graphite-gtk-theme-git
yay -S --noconfirm --needed greetd
yay -S --noconfirm --needed greetd-regreet
yay -S --noconfirm --needed grilo-plugins
yay -S --noconfirm --needed grim
yay -S --noconfirm --needed grml-zsh-config
yay -S --noconfirm --needed grub
yay -S --noconfirm --needed grub-btrfs
yay -S --noconfirm --needed grub-customizer
yay -S --noconfirm --needed gruvbox
yay -S --noconfirm --needed gsfonts
yay -S --noconfirm --needed gst-libav
yay -S --noconfirm --needed gst-plugin-pipewire
yay -S --noconfirm --needed gst-plugins-bad
yay -S --noconfirm --needed gst-plugins-base
yay -S --noconfirm --needed gst-plugins-good
yay -S --noconfirm --needed gst-plugins-ugly
yay -S --noconfirm --needed gstreamer
yay -S --noconfirm --needed gstreamer-vaapi
yay -S --noconfirm --needed gtk-engine-murrine
yay -S --noconfirm --needed gtkhash-thunar
yay -S --noconfirm --needed gufw
yay -S --noconfirm --needed gutenprint
yay -S --noconfirm --needed gvfs
yay -S --noconfirm --needed gvfs-afc
yay -S --noconfirm --needed gvfs-dnssd
yay -S --noconfirm --needed gvfs-goa
yay -S --noconfirm --needed gvfs-google
yay -S --noconfirm --needed gvfs-gphoto2
yay -S --noconfirm --needed gvfs-mtp
yay -S --noconfirm --needed gvfs-nfs
yay -S --noconfirm --needed gvfs-onedrive
yay -S --noconfirm --needed gvfs-smb
yay -S --noconfirm --needed gvfs-wsdd
yay -S --noconfirm --needed hardinfo2
yay -S --noconfirm --needed hdparm
yay -S --noconfirm --needed heroic-games-launcher-bin
yay -S --noconfirm --needed hexchat
yay -S --noconfirm --needed hplip
yay -S --noconfirm --needed htop
yay -S --noconfirm --needed hunspell-fr
yay -S --noconfirm --needed hw-probe
yay -S --noconfirm --needed hwinfo
yay -S --noconfirm --needed hydrogen
yay -S --noconfirm --needed hyperv
yay -S --noconfirm --needed ifuse
yay -S --noconfirm --needed imagemagick
yay -S --noconfirm --needed imdb-thumbnailer
yay -S --noconfirm --needed imv
yay -S --noconfirm --needed indentLine
yay -S --noconfirm --needed inkscape
yay -S --noconfirm --needed insync-thunar
yay -S --noconfirm --needed intel-ucode
yay -S --noconfirm --needed inxi
yay -S --noconfirm --needed irssi
yay -S --noconfirm --needed iw
yay -S --noconfirm --needed iwd
yay -S --noconfirm --needed jacktrip
yay -S --noconfirm --needed jfsutils
yay -S --noconfirm --needed jq
yay -S --noconfirm --needed jre8-openjdk
yay -S --noconfirm --needed kate
yay -S --noconfirm --needed kazam
yay -S --noconfirm --needed kdenlive
yay -S --noconfirm --needed keepassxc
yay -S --noconfirm --needed kitty
yay -S --noconfirm --needed kitty-terminfo
yay -S --noconfirm --needed konsole
yay -S --noconfirm --needed krita
yay -S --noconfirm --needed kvantum
yay -S --noconfirm --needed kvantum-theme-materia
yay -S --noconfirm --needed kvantum-theme-qogir-git
yay -S --noconfirm --needed languagetool
yay -S --noconfirm --needed laptop-detect
yay -S --noconfirm --needed layan-gtk-theme-git
yay -S --noconfirm --needed ldns
yay -S --noconfirm --needed leafpad
yay -S --noconfirm --needed less
yay -S --noconfirm --needed lftp
yay -S --noconfirm --needed lib32-libva-mesa-driver
yay -S --noconfirm --needed lib32-mesa-vdpau
yay -S --noconfirm --needed lib32-vulkan-mesa-layers
yay -S --noconfirm --needed lib32-vulkan-radeon
yay -S --noconfirm --needed libfido2
yay -S --noconfirm --needed libmythes
yay -S --noconfirm --needed libpipewire
yay -S --noconfirm --needed libpulse
yay -S --noconfirm --needed libreoffice-fresh
yay -S --noconfirm --needed libusb-compat
yay -S --noconfirm --needed libva-mesa-driver
yay -S --noconfirm --needed libxinerama
yay -S --noconfirm --needed light
yay -S --noconfirm --needed linux
yay -S --noconfirm --needed linux-atm
yay -S --noconfirm --needed linux-cachyos-lts
yay -S --noconfirm --needed linux-cachyos-lts-headers
yay -S --noconfirm --needed linux-firmware
yay -S --noconfirm --needed linux-firmware-marvell
yay -S --noconfirm --needed linux-headers
yay -S --noconfirm --needed linux-lts
yay -S --noconfirm --needed linux-lts-headers
yay -S --noconfirm --needed linux-zen
yay -S --noconfirm --needed linux-zen-headers
yay -S --noconfirm --needed livecd-sounds
yay -S --noconfirm --needed lmms
yay -S --noconfirm --needed logrotate
yay -S --noconfirm --needed lohit-fonts
yay -S --noconfirm --needed lolcat
yay -S --noconfirm --needed loupe
yay -S --noconfirm --needed lsb-release
yay -S --noconfirm --needed lsd
yay -S --noconfirm --needed lshw
yay -S --noconfirm --needed lsp-plugins-lv2
yay -S --noconfirm --needed lsscsi
yay -S --noconfirm --needed lutris
yay -S --noconfirm --needed lvm2
yay -S --noconfirm --needed lxappearance
yay -S --noconfirm --needed lxmusic
yay -S --noconfirm --needed lynx
yay -S --noconfirm --needed make
yay -S --noconfirm --needed mako
yay -S --noconfirm --needed malcontent
yay -S --noconfirm --needed man-db
yay -S --noconfirm --needed man-pages
yay -S --noconfirm --needed mangohud
yay -S --noconfirm --needed materia-gtk-theme
yay -S --noconfirm --needed mc
yay -S --noconfirm --needed mda.lv2
yay -S --noconfirm --needed mdadm
yay -S --noconfirm --needed megasync-bin
yay -S --noconfirm --needed meld
yay -S --noconfirm --needed memtest86+
yay -S --noconfirm --needed memtest86+-efi
yay -S --noconfirm --needed mesa
yay -S --noconfirm --needed meson
yay -S --noconfirm --needed micro
yay -S --noconfirm --needed microsoft-edge-stable-bin
yay -S --noconfirm --needed mission-center
yay -S --noconfirm --needed mixxx
yay -S --noconfirm --needed mkinitcpio
yay -S --noconfirm --needed mkinitcpio-archiso
yay -S --noconfirm --needed mkinitcpio-firmware
yay -S --noconfirm --needed mkinitcpio-nfs-utils
yay -S --noconfirm --needed mkinitcpio-openswap
yay -S --noconfirm --needed mobile-broadband-provider-info
yay -S --noconfirm --needed modemmanager
yay -S --noconfirm --needed most
yay -S --noconfirm --needed mousepad
yay -S --noconfirm --needed mousetweaks
yay -S --noconfirm --needed mpc
yay -S --noconfirm --needed mpd
yay -S --noconfirm --needed mpv
yay -S --noconfirm --needed mpv-mpris
yay -S --noconfirm --needed mtools
yay -S --noconfirm --needed mtpfs
yay -S --noconfirm --needed mugshot
yay -S --noconfirm --needed muse
yay -S --noconfirm --needed mythes-en
yay -S --noconfirm --needed nano
yay -S --noconfirm --needed nautilus
yay -S --noconfirm --needed navi
yay -S --noconfirm --needed nbd
yay -S --noconfirm --needed ncmpcpp
yay -S --noconfirm --needed ndisc6
yay -S --noconfirm --needed neofetch
yay -S --noconfirm --needed neovim
yay -S --noconfirm --needed neovim-coc-zsh-git
yay -S --noconfirm --needed nerd-fonts-source-code-pro
yay -S --noconfirm --needed nerdtree
yay -S --noconfirm --needed net-tools
yay -S --noconfirm --needed network-manager-applet
yay -S --noconfirm --needed networkmanager
yay -S --noconfirm --needed networkmanager-openconnect
yay -S --noconfirm --needed networkmanager-openvpn
yay -S --noconfirm --needed networkmanager-pptp
yay -S --noconfirm --needed networkmanager-vpnc
yay -S --noconfirm --needed newsboat
yay -S --noconfirm --needed nfs-utils
yay -S --noconfirm --needed nilfs-utils
yay -S --noconfirm --needed nitrogen
yay -S --noconfirm --needed nlohmann-json
yay -S --noconfirm --needed nmap
yay -S --noconfirm --needed noto-fonts
yay -S --noconfirm --needed noto-fonts-cjk
yay -S --noconfirm --needed noto-fonts-emoji
yay -S --noconfirm --needed noto-fonts-extra
yay -S --noconfirm --needed nss-mdns
yay -S --noconfirm --needed ntfs-3g
yay -S --noconfirm --needed ntp
yay -S --noconfirm --needed numix-gtk-theme-git
yay -S --noconfirm --needed numlockx
yay -S --noconfirm --needed nvme-cli
yay -S --noconfirm --needed nvtop
yay -S --noconfirm --needed nwg-bar
yay -S --noconfirm --needed nwg-dock
yay -S --noconfirm --needed nwg-drawer
yay -S --noconfirm --needed nwg-launchers
yay -S --noconfirm --needed nwg-look
yay -S --noconfirm --needed nwg-panel
yay -S --noconfirm --needed nwg-shell-git
yay -S --noconfirm --needed obs-studio
yay -S --noconfirm --needed octopi
yay -S --noconfirm --needed oh-my-posh-bin
yay -S --noconfirm --needed oh-my-zsh-powerline-theme-git
yay -S --noconfirm --needed okular
yay -S --noconfirm --needed open-iscsi
yay -S --noconfirm --needed open-vm-tools
yay -S --noconfirm --needed openconnect
yay -S --noconfirm --needed openresolv
yay -S --noconfirm --needed openrgb
yay -S --noconfirm --needed openshot
yay -S --noconfirm --needed openssh
yay -S --noconfirm --needed openvpn
yay -S --noconfirm --needed opera
yay -S --noconfirm --needed orca
yay -S --noconfirm --needed os-prober
yay -S --noconfirm --needed otf-font-awesome
yay -S --noconfirm --needed otf-libertinus
yay -S --noconfirm --needed p7zip
yay -S --noconfirm --needed pacman-contrib
yay -S --noconfirm --needed pacseek
yay -S --noconfirm --needed pamixer
yay -S --noconfirm --needed parole
yay -S --noconfirm --needed partclone
yay -S --noconfirm --needed parted
yay -S --noconfirm --needed partimage
yay -S --noconfirm --needed paru
yay -S --noconfirm --needed pavucontrol
yay -S --noconfirm --needed pcsclite
yay -S --noconfirm --needed pdfarranger
yay -S --noconfirm --needed pev
yay -S --noconfirm --needed picom
yay -S --noconfirm --needed pikaur
yay -S --noconfirm --needed pikaur-git
yay -S --noconfirm --needed piper
yay -S --noconfirm --needed pipewire
yay -S --noconfirm --needed pipewire-alsa
yay -S --noconfirm --needed pipewire-jack
yay -S --noconfirm --needed pipewire-pulse
yay -S --noconfirm --needed pkgfile
yay -S --noconfirm --needed plank
yay -S --noconfirm --needed playerctl
yay -S --noconfirm --needed playonlinux
yay -S --noconfirm --needed plocate
yay -S --noconfirm --needed pokemon-colorscripts-git
yay -S --noconfirm --needed polkit-gnome
yay -S --noconfirm --needed polybar
yay -S --noconfirm --needed power-profiles-daemon
yay -S --noconfirm --needed powerpill
yay -S --noconfirm --needed ppp
yay -S --noconfirm --needed pptpclient
yay -S --noconfirm --needed protontricks
yay -S --noconfirm --needed protonup-qt
yay -S --noconfirm --needed pulsemixer
yay -S --noconfirm --needed pv
yay -S --noconfirm --needed python-pyparted
yay -S --noconfirm --needed python-pyquery
yay -S --noconfirm --needed python-requests
yay -S --noconfirm --needed python-ttkbootstrap
yay -S --noconfirm --needed qalculate-gtk
yay -S --noconfirm --needed qbittorrent
yay -S --noconfirm --needed qemu-guest-agent
yay -S --noconfirm --needed qogir-gtk-theme-git
yay -S --noconfirm --needed qpwgraph
yay -S --noconfirm --needed qsynth
yay -S --noconfirm --needed qt5
yay -S --noconfirm --needed qt5-3d
yay -S --noconfirm --needed qt5-charts
yay -S --noconfirm --needed qt5-connectivity
yay -S --noconfirm --needed qt5-datavis3d
yay -S --noconfirm --needed qt5-doc
yay -S --noconfirm --needed qt5-examples
yay -S --noconfirm --needed qt5-graphicaleffects
yay -S --noconfirm --needed qt5-imageformats
yay -S --noconfirm --needed qt5-networkauth
yay -S --noconfirm --needed qt5-quick3d
yay -S --noconfirm --needed qt5-quickcontrols2
yay -S --noconfirm --needed qt5-remoteobjects
yay -S --noconfirm --needed qt5-scxml
yay -S --noconfirm --needed qt5-sensors
yay -S --noconfirm --needed qt5-serialport
yay -S --noconfirm --needed qt5-speech
yay -S --noconfirm --needed qt5-tools
yay -S --noconfirm --needed qt5-virtualkeyboard
yay -S --noconfirm --needed qt5-wayland
yay -S --noconfirm --needed qt5-websockets
yay -S --noconfirm --needed qt5ct
yay -S --noconfirm --needed qt6ct
yay -S --noconfirm --needed qtcreator
yay -S --noconfirm --needed qtractor
yay -S --noconfirm --needed ranger
yay -S --noconfirm --needed rate-mirrors
yay -S --noconfirm --needed rate-mirrors-bin
yay -S --noconfirm --needed realtime-privileges
yay -S --noconfirm --needed rebuild-detector
yay -S --noconfirm --needed redshift
yay -S --noconfirm --needed refind
yay -S --noconfirm --needed reflector
yay -S --noconfirm --needed reiserfsprogs
yay -S --noconfirm --needed replay-sorcery
yay -S --noconfirm --needed retroarch
yay -S --noconfirm --needed ripgrep-all
yay -S --noconfirm --needed ristretto
yay -S --noconfirm --needed rnnoise
yay -S --noconfirm --needed rocm-hip-runtime
yay -S --noconfirm --needed rocm-opencl-runtime
yay -S --noconfirm --needed rofi-calc
yay -S --noconfirm --needed rofi-lbonn-wayland
yay -S --noconfirm --needed rp-pppoe
yay -S --noconfirm --needed rsync
yay -S --noconfirm --needed rtkit
yay -S --noconfirm --needed rtl8821cu-morrownr-dkms-git
yay -S --noconfirm --needed rxvt-unicode-terminfo
yay -S --noconfirm --needed rygel
yay -S --noconfirm --needed samba
yay -S --noconfirm --needed sane
yay -S --noconfirm --needed sardi-icons
yay -S --noconfirm --needed sassc
yay -S --noconfirm --needed screen
yay -S --noconfirm --needed scrot
yay -S --noconfirm --needed scummvm
yay -S --noconfirm --needed sddm
yay -S --noconfirm --needed sdparm
yay -S --noconfirm --needed sg3_utils
yay -S --noconfirm --needed sgsearch
yay -S --noconfirm --needed shairport-sync
yay -S --noconfirm --needed shotwell
yay -S --noconfirm --needed simple-scan
yay -S --noconfirm --needed simplescreenrecorder
yay -S --noconfirm --needed slurp
yay -S --noconfirm --needed smartmontools
yay -S --noconfirm --needed smplayer
yay -S --noconfirm --needed snapd
yay -S --noconfirm --needed snapshot
yay -S --noconfirm --needed sof-firmware
yay -S --noconfirm --needed sofirem-git
yay -S --noconfirm --needed sparklines-git
yay -S --noconfirm --needed speex
yay -S --noconfirm --needed speexdsp
yay -S --noconfirm --needed splix
yay -S --noconfirm --needed spotify
yay -S --noconfirm --needed spotify-launcher
yay -S --noconfirm --needed squashfs-tools
yay -S --noconfirm --needed starship
yay -S --noconfirm --needed stow
yay -S --noconfirm --needed strace
yay -S --noconfirm --needed sublime-text-4
yay -S --noconfirm --needed sudo
yay -S --noconfirm --needed surfn-icons-git
yay -S --noconfirm --needed sushi
yay -S --noconfirm --needed swappy
yay -S --noconfirm --needed sway-git
yay -S --noconfirm --needed swaybg
yay -S --noconfirm --needed swayfx
yay -S --noconfirm --needed swayidle
yay -S --noconfirm --needed swaylock
yay -S --noconfirm --needed swaylock-effects
yay -S --noconfirm --needed sweet-cursor-theme-git
yay -S --noconfirm --needed sweet-gtk-theme-dark
yay -S --noconfirm --needed swww
yay -S --noconfirm --needed syslinux
yay -S --noconfirm --needed sysstat
yay -S --noconfirm --needed system-config-printer
yay -S --noconfirm --needed systemd-resolvconf
yay -S --noconfirm --needed tagbar
yay -S --noconfirm --needed taskell
yay -S --noconfirm --needed tcpdump
yay -S --noconfirm --needed tecla
yay -S --noconfirm --needed terminus-font
yay -S --noconfirm --needed testdisk
yay -S --noconfirm --needed the_silver_searcher
yay -S --noconfirm --needed thunar
yay -S --noconfirm --needed thunar-archive-plugin
yay -S --noconfirm --needed thunar-archive-plugin-git
yay -S --noconfirm --needed thunar-dropbox
yay -S --noconfirm --needed thunar-media-tags-plugin
yay -S --noconfirm --needed thunar-media-tags-plugin-git
yay -S --noconfirm --needed thunar-megasync-bin
yay -S --noconfirm --needed thunar-nextcloud-plugin
yay -S --noconfirm --needed thunar-nilfs2-plugin-git
yay -S --noconfirm --needed thunar-sendto-clamtk
yay -S --noconfirm --needed thunar-shares-plugin
yay -S --noconfirm --needed thunar-shares-plugin-git
yay -S --noconfirm --needed thunar-vcs-plugin
yay -S --noconfirm --needed thunar-vcs-plugin-git
yay -S --noconfirm --needed thunar-volman
yay -S --noconfirm --needed thunar-volman-devel
yay -S --noconfirm --needed thunar-volman-git
yay -S --noconfirm --needed thunarx-python
yay -S --noconfirm --needed thunderbird
yay -S --noconfirm --needed timeshift
yay -S --noconfirm --needed timeshift-autosnap
yay -S --noconfirm --needed tk
yay -S --noconfirm --needed tmux
yay -S --noconfirm --needed tokyonight-gtk-theme-git
yay -S --noconfirm --needed totem
yay -S --noconfirm --needed tpm2-tss
yay -S --noconfirm --needed ttf-anonymous-pro
yay -S --noconfirm --needed ttf-bitstream-vera
yay -S --noconfirm --needed ttf-caladea
yay -S --noconfirm --needed ttf-carlito
yay -S --noconfirm --needed ttf-cascadia-code
yay -S --noconfirm --needed ttf-cormorant
yay -S --noconfirm --needed ttf-croscore
yay -S --noconfirm --needed ttf-dejavu
yay -S --noconfirm --needed ttf-droid
yay -S --noconfirm --needed ttf-eurof
yay -S --noconfirm --needed ttf-fantasque-sans-mono
yay -S --noconfirm --needed ttf-fira-code
yay -S --noconfirm --needed ttf-fira-mono
yay -S --noconfirm --needed ttf-fira-sans
yay -S --noconfirm --needed ttf-font-awesome
yay -S --noconfirm --needed ttf-hack
yay -S --noconfirm --needed ttf-hactor
yay -S --noconfirm --needed ttf-hellvetica
yay -S --noconfirm --needed ttf-ibm-plex
yay -S --noconfirm --needed ttf-inconsolata
yay -S --noconfirm --needed ttf-iosevka-nerd
yay -S --noconfirm --needed ttf-jetbrains-mono
yay -S --noconfirm --needed ttf-jetbrains-mono-nerd
yay -S --noconfirm --needed ttf-joypixels
yay -S --noconfirm --needed ttf-lato
yay -S --noconfirm --needed ttf-liberation
yay -S --noconfirm --needed ttf-linux-libertine
yay -S --noconfirm --needed ttf-linux-libertine-g
yay -S --noconfirm --needed ttf-mac-fonts
yay -S --noconfirm --needed ttf-meslo-nerd
yay -S --noconfirm --needed ttf-meslo-nerd-font-powerlevel10k
yay -S --noconfirm --needed ttf-monofur
yay -S --noconfirm --needed ttf-ms-fonts
yay -S --noconfirm --needed ttf-nerd-fonts-symbols
yay -S --noconfirm --needed ttf-nerd-fonts-symbols-mono
yay -S --noconfirm --needed ttf-opensans
yay -S --noconfirm --needed ttf-roboto
yay -S --noconfirm --needed ttf-roboto-mono
yay -S --noconfirm --needed ttf-sourcecodepro-nerd
yay -S --noconfirm --needed ttf-ubuntu-font-family
yay -S --noconfirm --needed tumbler
yay -S --noconfirm --needed udate-grub
yay -S --noconfirm --needed udftools
yay -S --noconfirm --needed udiskie
yay -S --noconfirm --needed udisks2
yay -S --noconfirm --needed ueberzug
yay -S --noconfirm --needed ufw
yay -S --noconfirm --needed ulauncher
yay -S --noconfirm --needed unrar
yay -S --noconfirm --needed upd72020x-fw
yay -S --noconfirm --needed update-grub
yay -S --noconfirm --needed usb_modeswitch
yay -S --noconfirm --needed usbmuxd
yay -S --noconfirm --needed usbutils
yay -S --noconfirm --needed variety
yay -S --noconfirm --needed ventoy-bin
yay -S --noconfirm --needed vim
yay -S --noconfirm --needed vim-airline
yay -S --noconfirm --needed vim-airline-themes
yay -S --noconfirm --needed vim-devicons
yay -S --noconfirm --needed vim-hexokinase
yay -S --noconfirm --needed vim-polyglot
yay -S --noconfirm --needed vim-startify
yay -S --noconfirm --needed vimix-cursors
yay -S --noconfirm --needed vimix-gtk-themes
yay -S --noconfirm --needed vimix-icon-theme
yay -S --noconfirm --needed virtualbox
yay -S --noconfirm --needed visual-studio-code-bin
yay -S --noconfirm --needed vivaldi
yay -S --noconfirm --needed vivaldi-ffmpeg-codecs
yay -S --noconfirm --needed vivaldi-widevine
yay -S --noconfirm --needed vkbasalt
yay -S --noconfirm --needed vlc
yay -S --noconfirm --needed volumeicon
yay -S --noconfirm --needed vpnc
yay -S --noconfirm --needed vscodium
yay -S --noconfirm --needed vulkan-radeon
yay -S --noconfirm --needed waybar
yay -S --noconfirm --needed wayland-protocols
yay -S --noconfirm --needed wayland-utils
yay -S --noconfirm --needed wd719x-firmware
yay -S --noconfirm --needed we10x-icon-theme-git
yay -S --noconfirm --needed wf-recorder
yay -S --noconfirm --needed wget
yay -S --noconfirm --needed whitesur-icon-theme-git
yay -S --noconfirm --needed winetricks
yay -S --noconfirm --needed wireless-regdb
yay -S --noconfirm --needed wireless_tools
yay -S --noconfirm --needed wireplumber
yay -S --noconfirm --needed wl-clipboard
yay -S --noconfirm --needed wlogout
yay -S --noconfirm --needed wlr-randr
yay -S --noconfirm --needed wlroots
yay -S --noconfirm --needed wlsunset
yay -S --noconfirm --needed wofi
yay -S --noconfirm --needed wpa_supplicant
yay -S --noconfirm --needed wvdial
yay -S --noconfirm --needed xarchiver
yay -S --noconfirm --needed xarchiver-gtk2
yay -S --noconfirm --needed xclip
yay -S --noconfirm --needed xdg-desktop-portal-gtk
yay -S --noconfirm --needed xdg-desktop-portal-wlr
yay -S --noconfirm --needed xdg-desktop-portal-xapp
yay -S --noconfirm --needed xdg-user-dirs
yay -S --noconfirm --needed xdg-user-dirs-gtk
yay -S --noconfirm --needed xdg-utils
yay -S --noconfirm --needed xdiff-ext-git
yay -S --noconfirm --needed xdotool
yay -S --noconfirm --needed xed
yay -S --noconfirm --needed xf86-input-elographics
yay -S --noconfirm --needed xf86-input-libinput
yay -S --noconfirm --needed xf86-video-amdgpu
yay -S --noconfirm --needed xf86-video-ati
yay -S --noconfirm --needed xf86-video-nouveau
yay -S --noconfirm --needed xf86-video-vmware
yay -S --noconfirm --needed xfburn
yay -S --noconfirm --needed xfce4-appfinder
yay -S --noconfirm --needed xfce4-artwork
yay -S --noconfirm --needed xfce4-battery-plugin
yay -S --noconfirm --needed xfce4-clipman-plugin
yay -S --noconfirm --needed xfce4-cpufreq-plugin
yay -S --noconfirm --needed xfce4-cpugraph-plugin
yay -S --noconfirm --needed xfce4-dict
yay -S --noconfirm --needed xfce4-diskperf-plugin
yay -S --noconfirm --needed xfce4-eyes-plugin
yay -S --noconfirm --needed xfce4-fsguard-plugin
yay -S --noconfirm --needed xfce4-genmon-plugin
yay -S --noconfirm --needed xfce4-mailwatch-plugin
yay -S --noconfirm --needed xfce4-mount-plugin
yay -S --noconfirm --needed xfce4-mpc-plugin
yay -S --noconfirm --needed xfce4-netload-plugin
yay -S --noconfirm --needed xfce4-notes-plugin
yay -S --noconfirm --needed xfce4-notifyd
yay -S --noconfirm --needed xfce4-panel
yay -S --noconfirm --needed xfce4-places-plugin
yay -S --noconfirm --needed xfce4-power-manager
yay -S --noconfirm --needed xfce4-pulseaudio-plugin
yay -S --noconfirm --needed xfce4-screensaver
yay -S --noconfirm --needed xfce4-screenshooter
yay -S --noconfirm --needed xfce4-sensors-plugin
yay -S --noconfirm --needed xfce4-session
yay -S --noconfirm --needed xfce4-settings
yay -S --noconfirm --needed xfce4-smartbookmark-plugin
yay -S --noconfirm --needed xfce4-systemload-plugin
yay -S --noconfirm --needed xfce4-taskmanager
yay -S --noconfirm --needed xfce4-terminal
yay -S --noconfirm --needed xfce4-time-out-plugin
yay -S --noconfirm --needed xfce4-timer-plugin
yay -S --noconfirm --needed xfce4-verve-plugin
yay -S --noconfirm --needed xfce4-wavelan-plugin
yay -S --noconfirm --needed xfce4-weather-plugin
yay -S --noconfirm --needed xfce4-whiskermenu-plugin
yay -S --noconfirm --needed xfce4-xkb-plugin
yay -S --noconfirm --needed xfconf
yay -S --noconfirm --needed xfdesktop
yay -S --noconfirm --needed xfsprogs
yay -S --noconfirm --needed xfwm4
yay -S --noconfirm --needed xfwm4-themes
yay -S --noconfirm --needed xl2tpd
yay -S --noconfirm --needed xorg-bdftopcf
yay -S --noconfirm --needed xorg-iceauth
yay -S --noconfirm --needed xorg-mkfontscale
yay -S --noconfirm --needed xorg-server
yay -S --noconfirm --needed xorg-sessreg
yay -S --noconfirm --needed xorg-setxkbmap
yay -S --noconfirm --needed xorg-smproxy
yay -S --noconfirm --needed xorg-x11perf
yay -S --noconfirm --needed xorg-xauth
yay -S --noconfirm --needed xorg-xbacklight
yay -S --noconfirm --needed xorg-xcmsdb
yay -S --noconfirm --needed xorg-xcursorgen
yay -S --noconfirm --needed xorg-xdpyinfo
yay -S --noconfirm --needed xorg-xdriinfo
yay -S --noconfirm --needed xorg-xev
yay -S --noconfirm --needed xorg-xgamma
yay -S --noconfirm --needed xorg-xhost
yay -S --noconfirm --needed xorg-xinit
yay -S --noconfirm --needed xorg-xinput
yay -S --noconfirm --needed xorg-xkbcomp
yay -S --noconfirm --needed xorg-xkbevd
yay -S --noconfirm --needed xorg-xkbprint
yay -S --noconfirm --needed xorg-xkbutils
yay -S --noconfirm --needed xorg-xkill
yay -S --noconfirm --needed xorg-xlsatoms
yay -S --noconfirm --needed xorg-xlsclients
yay -S --noconfirm --needed xorg-xmodmap
yay -S --noconfirm --needed xorg-xpr
yay -S --noconfirm --needed xorg-xprop
yay -S --noconfirm --needed xorg-xrandr
yay -S --noconfirm --needed xorg-xrdb
yay -S --noconfirm --needed xorg-xrefresh
yay -S --noconfirm --needed xorg-xset
yay -S --noconfirm --needed xorg-xsetroot
yay -S --noconfirm --needed xorg-xvinfo
yay -S --noconfirm --needed xorg-xwayland
yay -S --noconfirm --needed xorg-xwd
yay -S --noconfirm --needed xorg-xwininfo
yay -S --noconfirm --needed xorg-xwud
yay -S --noconfirm --needed xpadneo-dkms-git
yay -S --noconfirm --needed xpdf
yay -S --noconfirm --needed xreader
yay -S --noconfirm --needed xsettingsd
yay -S --noconfirm --needed xss-lock
yay -S --noconfirm --needed yad
yay -S --noconfirm --needed yaru-icon-theme
yay -S --noconfirm --needed yay
yay -S --noconfirm --needed yelp
yay -S --noconfirm --needed youtube-dl-gui-git
yay -S --noconfirm --needed yt-dlp
yay -S --noconfirm --needed yt-dlp-drop-in
yay -S --noconfirm --needed yt-dlp-git
yay -S --noconfirm --needed zam-plugins-lv2
yay -S --noconfirm --needed zathura
yay -S --noconfirm --needed zita-convolver
yay -S --noconfirm --needed zram-generator
yay -S --noconfirm --needed zsh
yay -S --noconfirm --needed zsh-completions


###### Browsers ########
yay -S --noconfirm --needed brave-bin
yay -S --noconfirm --needed microsoft-edge-stable-bin
yay -S --noconfirm --needed vivaldi
yay -S --noconfirm --needed vivaldi-ffmpeg-codecs
yay -S --noconfirm --needed opera
yay -S --noconfirm --needed google-chrome
yay -S --noconfirm --needed firefox

###### Firewall installs ####
sudo ufw enable
sudo ufw status verbose
sudo systemctl enable ufw.service
sudo systemctl enable fstrim.timer
sudo systemctl start fstrim.timer
du -sh /var/cache/pacman/pkg/
sudo pacman -S -y pacman-contrib
sudo systemctl enable paccache.timer

###### Flatpaks installs ####
flatpak install flathub com.github.tchx84.Flatseal --assumeyes  --or-update --system
flatpak install flathub fr.natron.Natron --assumeyes  --or-update --system
flatpak install flathub com.protonvpn.www --assumeyes  --or-update --system
flatpak install flathub me.proton.Pass --assumeyes  --or-update --system
sudo pacman -Syyu && sudo pacman -Syu

###### ZSH ########
yay -S --noconfirm --needed zsh
yay -S --noconfirm --needed zsh-completions
yay -S --noconfirm --needed grml-zsh-config
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
